"""Assemble the monthly analysis report (monthly_summary.txt).

The report combines:
- daily diagnostics (daily_diagnostics.csv from Fortran)
- monthly statistics (statistics.py)
- convective adjustment counters
- ERA5 forcing ranges

This is a reporting assembler only; all physics values come from the
Fortran model output and the earlier analysis scripts.
"""

import argparse
import pathlib

import pandas as pd

DEFAULT_DIAG = "data/output/daily_diagnostics.csv"
DEFAULT_STATS = "data/output/monthly_summary.txt"
DEFAULT_OUT = "data/output/monthly_report.txt"


def main():
    parser = argparse.ArgumentParser(description="Assemble the monthly analysis report.")
    parser.add_argument("--diag", default=DEFAULT_DIAG, help="Fortran daily diagnostics CSV")
    parser.add_argument("--stats", default=DEFAULT_STATS, help="monthly_summary.txt from statistics.py")
    parser.add_argument("--out", default=DEFAULT_OUT, help="Output report path")
    args = parser.parse_args()

    diag = pathlib.Path(args.diag)
    stats = pathlib.Path(args.stats)
    if not diag.exists():
        print(f"ERROR: {diag} not found. Run the Fortran model first.")
        return 1

    df = pd.read_csv(diag)
    if df.empty:
        print("ERROR: empty daily diagnostics.")
        return 1

    lines = []
    lines.append("=" * 72)
    lines.append("  AARI Iceberg Thermodynamic Model - Monthly Analysis Report")
    lines.append("=" * 72)
    lines.append("")

    lines.append("RUN OVERVIEW")
    lines.append(f"  Model days simulated : {len(df)}")
    lines.append(f"  First / last day     : {int(df['day'].min())} / {int(df['day'].max())}")
    lines.append("")

    lines.append("ENERGY")
    lines.append(f"  Kinetic energy EUU min/max/mean (cm2/s2): "
                 f"{df['euu'].min():.4e} / {df['euu'].max():.4e} / {df['euu'].mean():.4e}")
    lines.append("")

    lines.append("VELOCITIES (cm/s, min/max over all days)")
    for col, name in [("u", "U"), ("v", "V"), ("w", "W")]:
        lines.append(f"  {name}: {df[f'{col}_min'].min():.4e} .. {df[f'{col}_max'].max():.4e}")
    lines.append("")

    lines.append("THERMODYNAMICS (min/max over all days)")
    lines.append(f"  T : {df['t_min'].min():.4f} .. {df['t_max'].max():.4f} degC")
    lines.append(f"  S : {df['s_min'].min():.6f} .. {df['s_max'].max():.6f} (mass fraction)")
    lines.append(f"  RO: {df['ro_min'].min():.6e} .. {df['ro_max'].max():.6e} g/cm3")
    lines.append("")

    lines.append("FORCING")
    lines.append(f"  max wind speed : {df['wind_max'].max():.3f} m/s")
    lines.append(f"  tau_x range    : {df['tx_min'].min():.4f} .. {df['tx_max'].max():.4f} dyn/cm2")
    lines.append(f"  tau_y range    : {df['ty_min'].min():.4f} .. {df['ty_max'].max():.4f} dyn/cm2")
    lines.append("")

    lines.append("CONVECTIVE ADJUSTMENT (monitoring only, guard preserved)")
    lines.append(f"  total nmix (sum)     : {int(df['ca_nmix'].sum())}")
    lines.append(f"  max iterations/day   : {int(df['ca_max_iter'].max())}")
    lines.append(f"  guard hits (total)   : {int(df['ca_guard_hits'].sum())}")
    lines.append(f"  affected columns/day : {int(df['ca_affected_cols'].mean())}")
    lines.append("")

    if stats.exists():
        lines.append("MONTHLY STATISTICS")
        lines.append(stats.read_text(encoding="utf-8"))
        lines.append("")

    lines.append("=" * 72)
    lines.append("  Generated by python/analysis/generate_report.py")
    lines.append("=" * 72)

    out = pathlib.Path(args.out)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Report written to {args.out}")
    print("\n".join(lines[:30]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())