name: iceberg-thermodynamic-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Data acquisition (CDS API)
  - cdsapi
  # Analysis & visualization
  - xarray
  - netCDF4
  - numpy
  - pandas
  - matplotlib
  # Grid building & processing
  - scipy
  - pyproj
  - rasterio
  # LSP / Development Tools (Fortran)
  - pip
  - pip:
      - fortls
      - fprettify
